"""empty message

Revision ID: 08092299664d
Revises: 5625f65644a5
Create Date: 2017-11-20 12:05:22.472000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08092299664d'
down_revision = '5625f65644a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AdminLog', 'adminName',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ChapterInfo', 'courseId',
               existing_type=mysql.CHAR(length=8),
               nullable=False)
    op.alter_column('CourseDoc', 'chapId',
               existing_type=mysql.CHAR(length=15),
               nullable=False)
    op.alter_column('CourseInfo', 'typeId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('CourseRsc', 'chapId',
               existing_type=mysql.CHAR(length=15),
               nullable=False)
    op.alter_column('CourseType', 'Cou_typeId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('UserLog', 'userName',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserLog', 'userName',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('CourseType', 'Cou_typeId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('CourseRsc', 'chapId',
               existing_type=mysql.CHAR(length=15),
               nullable=True)
    op.alter_column('CourseInfo', 'typeId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('CourseDoc', 'chapId',
               existing_type=mysql.CHAR(length=15),
               nullable=True)
    op.alter_column('ChapterInfo', 'courseId',
               existing_type=mysql.CHAR(length=8),
               nullable=True)
    op.alter_column('AdminLog', 'adminName',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
