"""empty message

Revision ID: 5625f65644a5
Revises: 
Create Date: 2017-11-20 11:57:01.983000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5625f65644a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('adminName', sa.String(length=20), nullable=False),
    sa.Column('adminEmail', sa.String(length=64), nullable=False),
    sa.Column('adminPhone', sa.CHAR(length=11), nullable=False),
    sa.Column('adminPass', sa.CHAR(length=40), nullable=False),
    sa.Column('adminType', sa.CHAR(length=6), nullable=False),
    sa.Column('lastLogin', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('adminName')
    )
    op.create_table('CourseType',
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('Cou_typeId', sa.Integer(), nullable=True),
    sa.Column('typeName', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Cou_typeId'], ['CourseType.typeId'], ),
    sa.PrimaryKeyConstraint('typeId')
    )
    op.create_table('Log',
    sa.Column('logId', sa.CHAR(length=40), nullable=False),
    sa.Column('logTime', sa.DateTime(), nullable=False),
    sa.Column('logContent', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('logId')
    )
    op.create_table('User',
    sa.Column('userName', sa.String(length=20), nullable=False),
    sa.Column('userEmail', sa.String(length=64), nullable=False),
    sa.Column('userPhone', sa.CHAR(length=11), nullable=False),
    sa.Column('userPass', sa.CHAR(length=40), nullable=False),
    sa.Column('signUpDate', sa.DateTime(), nullable=True),
    sa.Column('lastLogin', sa.DateTime(), nullable=False),
    sa.Column('studyDuration', sa.Integer(), nullable=False),
    sa.Column('frozenDuration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('userName')
    )
    op.create_table('AdminLog',
    sa.Column('logId', sa.CHAR(length=40), nullable=False),
    sa.Column('adminName', sa.String(length=20), nullable=True),
    sa.Column('logTime', sa.DateTime(), nullable=False),
    sa.Column('logContent', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['adminName'], ['Admin.adminName'], ),
    sa.PrimaryKeyConstraint('logId')
    )
    op.create_table('CourseInfo',
    sa.Column('courseId', sa.CHAR(length=8), nullable=False),
    sa.Column('typeId', sa.Integer(), nullable=True),
    sa.Column('courseTitle', sa.String(length=64), nullable=False),
    sa.Column('courseTeacher', sa.String(length=20), nullable=False),
    sa.Column('coursePubTime', sa.DateTime(), nullable=False),
    sa.Column('courseAbstract', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['typeId'], ['CourseType.typeId'], ),
    sa.PrimaryKeyConstraint('courseId')
    )
    op.create_table('UserLog',
    sa.Column('logId', sa.CHAR(length=40), nullable=False),
    sa.Column('userName', sa.String(length=20), nullable=True),
    sa.Column('logTime', sa.DateTime(), nullable=False),
    sa.Column('logContent', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['userName'], ['User.userName'], ),
    sa.PrimaryKeyConstraint('logId')
    )
    op.create_table('ChapterInfo',
    sa.Column('chapId', sa.CHAR(length=15), nullable=False),
    sa.Column('courseId', sa.CHAR(length=8), nullable=True),
    sa.Column('chapName', sa.String(length=64), nullable=False),
    sa.Column('chapLayer', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['CourseInfo.courseId'], ),
    sa.PrimaryKeyConstraint('chapId')
    )
    op.create_table('Comments',
    sa.Column('cmtId', sa.CHAR(length=10), nullable=False),
    sa.Column('userName', sa.String(length=20), nullable=False),
    sa.Column('chapId', sa.CHAR(length=15), nullable=False),
    sa.Column('cmtContent', sa.Text(), nullable=False),
    sa.Column('submitTime', sa.DateTime(), nullable=False),
    sa.Column('isVisible', sa.CHAR(length=5), nullable=False),
    sa.ForeignKeyConstraint(['chapId'], ['ChapterInfo.chapId'], ),
    sa.ForeignKeyConstraint(['userName'], ['User.userName'], ),
    sa.PrimaryKeyConstraint('cmtId')
    )
    op.create_table('CourseDoc',
    sa.Column('MD5', sa.CHAR(length=40), nullable=False),
    sa.Column('chapId', sa.CHAR(length=15), nullable=True),
    sa.Column('fileName', sa.String(length=64), nullable=False),
    sa.Column('filePath', sa.String(length=256), nullable=False),
    sa.Column('fileSize', sa.Integer(), nullable=False),
    sa.Column('uploadTime', sa.DateTime(), nullable=False),
    sa.Column('fileExt', sa.CHAR(length=4), nullable=False),
    sa.Column('isDoc', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chapId'], ['ChapterInfo.chapId'], ),
    sa.PrimaryKeyConstraint('MD5')
    )
    op.create_table('CourseRsc',
    sa.Column('MD5', sa.CHAR(length=40), nullable=False),
    sa.Column('chapId', sa.CHAR(length=15), nullable=True),
    sa.Column('fileName', sa.String(length=64), nullable=False),
    sa.Column('filePath', sa.String(length=256), nullable=False),
    sa.Column('fileSize', sa.Integer(), nullable=False),
    sa.Column('uploadTime', sa.DateTime(), nullable=False),
    sa.Column('fileExt', sa.CHAR(length=4), nullable=False),
    sa.Column('isDoc', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chapId'], ['ChapterInfo.chapId'], ),
    sa.PrimaryKeyConstraint('MD5')
    )
    op.create_table('CourseVideo',
    sa.Column('MD5', sa.CHAR(length=40), nullable=False),
    sa.Column('chapId', sa.CHAR(length=15), nullable=True),
    sa.Column('fileName', sa.String(length=64), nullable=False),
    sa.Column('filePath', sa.String(length=256), nullable=False),
    sa.Column('fileSize', sa.Integer(), nullable=False),
    sa.Column('uploadTime', sa.DateTime(), nullable=False),
    sa.Column('fileExt', sa.CHAR(length=4), nullable=False),
    sa.Column('isDoc', sa.Boolean(), nullable=False),
    sa.Column('videoDuration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapId'], ['ChapterInfo.chapId'], ),
    sa.PrimaryKeyConstraint('MD5')
    )
    op.create_table('StudyProgress',
    sa.Column('userName', sa.String(length=20), nullable=False),
    sa.Column('chapId', sa.CHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['chapId'], ['ChapterInfo.chapId'], ),
    sa.ForeignKeyConstraint(['userName'], ['User.userName'], ),
    sa.PrimaryKeyConstraint('userName', 'chapId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StudyProgress')
    op.drop_table('CourseVideo')
    op.drop_table('CourseRsc')
    op.drop_table('CourseDoc')
    op.drop_table('Comments')
    op.drop_table('ChapterInfo')
    op.drop_table('UserLog')
    op.drop_table('CourseInfo')
    op.drop_table('AdminLog')
    op.drop_table('User')
    op.drop_table('Log')
    op.drop_table('CourseType')
    op.drop_table('Admin')
    # ### end Alembic commands ###
