"""empty message

Revision ID: 8cf3ddd00791
Revises: 
Create Date: 2017-12-19 21:28:14.654000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cf3ddd00791'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comments', sa.Column('rep_cmtId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Comments', 'Comments', ['rep_cmtId'], ['cmtId'])
    op.drop_column('Comments', 'rep_comtId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comments', sa.Column('rep_comtId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Comments', type_='foreignkey')
    op.drop_column('Comments', 'rep_cmtId')
    # ### end Alembic commands ###
