"""empty message

Revision ID: e0dbc64d7886
Revises: f02b08c2ab79
Create Date: 2017-12-26 22:41:58.004000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0dbc64d7886'
down_revision = 'f02b08c2ab79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('courseImage', table_name='CourseInfo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('courseImage', 'CourseInfo', ['courseImage'], unique=True)
    # ### end Alembic commands ###
