"""empty message

Revision ID: f02b08c2ab79
Revises: 
Create Date: 2017-12-26 22:01:07.528000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f02b08c2ab79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'Comments_ibfk_3', 'Comments', type_='foreignkey')
    op.drop_constraint(u'Comments_ibfk_4', 'Comments', type_='foreignkey')
    op.drop_constraint(u'Comments_ibfk_1', 'Comments', type_='foreignkey')
    op.drop_constraint(u'Comments_ibfk_2', 'Comments', type_='foreignkey')
    op.create_foreign_key(None, 'Comments', 'ChapterInfo', ['chapId'], ['chapId'])
    op.create_foreign_key(None, 'Comments', 'Comments', ['rep_cmtId'], ['cmtId'])
    op.create_foreign_key(None, 'Comments', 'User', ['userName'], ['userName'])
    op.create_foreign_key(None, 'Comments', 'CourseInfo', ['courseId'], ['courseId'])
    op.drop_column('Comments', 'isVisible')
    op.drop_constraint(u'CourseDoc_ibfk_1', 'CourseDoc', type_='foreignkey')
    op.drop_constraint(u'CourseDoc_ibfk_2', 'CourseDoc', type_='foreignkey')
    op.create_foreign_key(None, 'CourseDoc', 'ChapterInfo', ['chapId'], ['chapId'])
    op.create_foreign_key(None, 'CourseDoc', 'CourseInfo', ['courseId'], ['courseId'])
    op.drop_constraint(u'CourseVideo_ibfk_2', 'CourseVideo', type_='foreignkey')
    op.drop_constraint(u'CourseVideo_ibfk_1', 'CourseVideo', type_='foreignkey')
    op.create_foreign_key(None, 'CourseVideo', 'ChapterInfo', ['chapId'], ['chapId'])
    op.create_foreign_key(None, 'CourseVideo', 'CourseInfo', ['courseId'], ['courseId'])
    op.drop_column('CourseVideo', 'videoDuration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CourseVideo', sa.Column('videoDuration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'CourseVideo', type_='foreignkey')
    op.drop_constraint(None, 'CourseVideo', type_='foreignkey')
    op.create_foreign_key(u'CourseVideo_ibfk_1', 'CourseVideo', 'ChapterInfo', ['chapId'], ['chapId'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'CourseVideo_ibfk_2', 'CourseVideo', 'CourseInfo', ['courseId'], ['courseId'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'CourseDoc', type_='foreignkey')
    op.drop_constraint(None, 'CourseDoc', type_='foreignkey')
    op.create_foreign_key(u'CourseDoc_ibfk_2', 'CourseDoc', 'CourseInfo', ['courseId'], ['courseId'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'CourseDoc_ibfk_1', 'CourseDoc', 'ChapterInfo', ['chapId'], ['chapId'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.add_column('Comments', sa.Column('isVisible', mysql.CHAR(length=5), nullable=False))
    op.drop_constraint(None, 'Comments', type_='foreignkey')
    op.drop_constraint(None, 'Comments', type_='foreignkey')
    op.drop_constraint(None, 'Comments', type_='foreignkey')
    op.drop_constraint(None, 'Comments', type_='foreignkey')
    op.create_foreign_key(u'Comments_ibfk_2', 'Comments', 'User', ['userName'], ['userName'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'Comments_ibfk_1', 'Comments', 'ChapterInfo', ['chapId'], ['chapId'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'Comments_ibfk_4', 'Comments', 'CourseInfo', ['courseId'], ['courseId'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'Comments_ibfk_3', 'Comments', 'Comments', ['rep_cmtId'], ['cmtId'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    # ### end Alembic commands ###
